#--                                                  /THIS FILE IS A PART OF RUBYCAMPUS/
# +------------------------------------------------------------------------------------+
# | RubyCampus - Student & Alumni Relationship Management Software                     |
# +------------------------------------------------------------------------------------+
# | Copyright (C) 2008 Kevin Aleman, RubyCampus LLC - https://rubycampus.org           |
# +------------------------------------------------------------------------------------+
# |                                                                                    |
# | This program is free software; you can redistribute it and/or modify it under the  |
# | terms of the GNU Affero General Public License version 3 as published by the Free  |
# | Software Foundation with the addition of the following permission added to Section |
# | 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK IN WHICH THE     |
# | COPYRIGHT IS OWNED BY RUBYCAMPUS LLC, RUBYCAMPUS LLC DISCLAIMS THE WARRANTY OF NON |
# | INFRINGEMENT OF THIRD PARTY RIGHTS.                                                |
# |                                                                                    |
# | This program is distributed in the hope that it will be useful, but WITHOUT ANY    |
# | WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A    |
# | PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.   |
# |                                                                                    |
# | You should have received a copy of the GNU Affero General Public License along     |
# | with this program; if not, see http://www.gnu.org/licenses or write to the Free    |
# | Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  |
# | USA.                                                                               |
# |                                                                                    |
# | You can contact RubyCampus, LLC. at email address project@rubycampus.org.          |
# |                                                                                    |
# | The interactive user interfaces in modified source and object code versions of     |
# | this program must display Appropriate Legal Notices, as required under Section 5   |
# | of the GNU Affero General Public License version 3.                                |
# |                                                                                    |
# | In accordance with Section 7(b) of the GNU Affero General Public License version   |
# | 3, these Appropriate Legal Notices must retain the display of the "Powered by      |
# | RubyCampus" logo. If the display of the logo is not reasonably feasible for        |
# | technical reasons, the Appropriate Legal Notices must display the words "Powered   |
# | by RubyCampus".                                                                    |
# +------------------------------------------------------------------------------------+
#++
#
# This file should not be edited, it is only used as a placeholder for application
# defaults. RubyCampus does not store YOUR settings in this file, those are stored
# within the database itself. Modifying this file without understanding how it is
# used by RubyCampus can have detrimental effects on your installation. Use the built-in
# settings manager provided within RubyCampus.
#
demo:
  default:  0
site_name:
  default:  RubyCampus
site_description:
  default:  Student & Alumni Relationship Management for Higher Education
site_protocol:
  default:  https://
site_domain:
  default:  demo.rubycampus.org
site_title_default:
  default:  Student & Alumni Relationship Management for Higher Education
site_title_login:
  default:  Welcome to RubyCampus
site_from_name:
  default: RubyCampus Project
site_from_email_address:
  default: project@rubycampus.org
site_from_email_domain:
  default:  rubycampus.org
site_from_email_return_path:
  default: project@rubycampus.org
site_street_address_line_1:
  default:  Fukuoka Tower
site_street_address_line_2:
  default:
site_street_address_line_3:
  default:
site_city:
  default:  Fukuoka City
site_postal_code:
  default:  814-0001
site_country:
  default:  Japan
site_state_or_province:
  default:  Fukuoka
site_preferred_email_address:
  default:  project@rubycampus.org
site_preferred_phone:
  default:
# start Data Services
# Moodle e-Learning Platform
moodle_enabled:
  default:  0
moodle_table_prefix:
  default:  'mdl_'
moodle_contact_table:
  default:  'user'
moodle_database_user:
  default:
moodle_database_password:
  default:
moodle_database_socket:
  default:
# Sakai CLE  
sakai_enabled:
  default:  0
sakai_table_prefix:
  default:
sakai_contact_table:
  default:
sakai_database_user:
  default:
sakai_database_password:
  default:      
sakai_database_socket:
  default:    
# Facebook API
facebook_enabled:
  default: 0
facebook_api_key:
  default:
facebook_canvas_page_name:
  default:
facebook_callback_url:
  default:
# end Data Services
encrypt_sensitive_attributes:
  default:  0
domain_gui_calender_theme:
  default: default
# FIXME Not implemented
geocodable_service_enabled:
  default: 0
geocodable_service_api_key:
  default:  ABQIAAAA_JjoUvqa134bquGy4vY15RRO4G5fyh1zZNzSCFmcvO7LZYRzsRT7v27fmOMDtR2bY8zj5aAhj8c8QQ
calendar_date_select_format:
  default: hyphen_ampm
# Outbound Mail
email_server_enabled:
  default: 0
email_server_smtp_address:
  default: 127.0.0.1
email_server_smtp_port:
  default: 25
email_server_smtp_domain:
  default: rubycampus.org
email_server_smtp_user_name:
  default:
email_server_smtp_password:
  default:
# RubyCampus Community
share_site_information_with_rubycampus:
  default: 0
automatically_check_for_rubycampus_version_updates:
  default: 1